QT       -= core gui
TARGET    = gifsicle

# config.h is generated by ./configure (which we do not use)
# but is generic enough that we can just vendor it.
DEFINES  += HAVE_CONFIG_H

# Do not build gifsicle.app
macx: CONFIG -= app_bundle

include(gifsicle.pri)
